// <auto-generated />
using System;
using MERSEL.Services.GibUserList.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MERSEL.Services.GibUserList.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GibUserListDbContext))]
    partial class GibUserListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MERSEL.Services.GibUserList.Domain.Entities.EDespatchGibUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_type");

                    b.Property<string>("AliasesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("aliases_json");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(32)
                        .HasColumnType("character(32)")
                        .HasColumnName("content_hash")
                        .IsFixedLength();

                    b.Property<DateTime>("FirstCreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("first_creation_time");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("identifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("TitleLower")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title_lower");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_e_despatch_gib_users");

                    b.ToTable((string)null);

                    b.ToView("mv_e_despatch_gib_users", (string)null);
                });

            modelBuilder.Entity("MERSEL.Services.GibUserList.Domain.Entities.EInvoiceGibUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_type");

                    b.Property<string>("AliasesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("aliases_json");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(32)
                        .HasColumnType("character(32)")
                        .HasColumnName("content_hash")
                        .IsFixedLength();

                    b.Property<DateTime>("FirstCreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("first_creation_time");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("identifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("TitleLower")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title_lower");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_e_invoice_gib_users");

                    b.ToTable((string)null);

                    b.ToView("mv_e_invoice_gib_users", (string)null);
                });

            modelBuilder.Entity("MERSEL.Services.GibUserList.Domain.Entities.GibUserChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_type");

                    b.Property<string>("AliasesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("aliases_json");

                    b.Property<short>("ChangeType")
                        .HasColumnType("smallint")
                        .HasColumnName("change_type");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changed_at");

                    b.Property<short>("DocumentType")
                        .HasColumnType("smallint")
                        .HasColumnName("document_type");

                    b.Property<DateTime?>("FirstCreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("first_creation_time");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("identifier");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_gib_user_changelog");

                    b.HasIndex("DocumentType", "ChangedAt")
                        .HasDatabaseName("ix_gib_user_changelog_document_type_changed_at");

                    b.ToTable("gib_user_changelog", (string)null);
                });

            modelBuilder.Entity("MERSEL.Services.GibUserList.Domain.Entities.SyncMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<int>("EDespatchUserCount")
                        .HasColumnType("integer")
                        .HasColumnName("e_despatch_user_count");

                    b.Property<int>("EInvoiceUserCount")
                        .HasColumnType("integer")
                        .HasColumnName("e_invoice_user_count");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_failure_at");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<TimeSpan>("LastSyncDuration")
                        .HasColumnType("interval")
                        .HasColumnName("last_sync_duration");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_sync_error");

                    b.Property<string>("LastSyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("last_sync_status");

                    b.HasKey("Key")
                        .HasName("pk_sync_metadata");

                    b.ToTable("sync_metadata", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
